import psgc from "@/data/psgc.json";

// Philippine Standard Geographic Code data, regenerated by scripts/fetch-psgc.mjs.
// City/municipality codes are unique nationwide, so geofencing compares codes, not names.

export type PsgcRegion = { code: string; name: string };
export type PsgcCity = { code: string; name: string };
export type PsgcProvince = { code: string; name: string; cities: PsgcCity[] };

export type ResolvedPlace = {
  regionCode: string;
  provinceCode: string;
  cityCode: string;
  region: string;
  province: string;
  city: string;
};

/** "Region I (Ilocos Region)", "National Capital Region", "CALABARZON (Region IV-A)"… */
function regionDisplayName(r: { name: string; label: string }) {
  if (r.label.startsWith("Region")) return r.name === r.label ? r.label : `${r.label} (${r.name})`;
  return r.label.length >= r.name.length ? r.label : r.name;
}

const regions: PsgcRegion[] = psgc.regions.map((r) => ({ code: r.code, name: regionDisplayName(r) }));
const regionsByCode = new Map(regions.map((r) => [r.code, r]));
const provincesByCode = new Map(psgc.provinces.map((p) => [p.code, p]));
const citiesByCode = new Map(psgc.cities.map((c) => [c.code, c]));

export function listRegions() {
  return regions;
}

/** Provinces of a region, each with its cities/municipalities (both sorted by name). */
export function getRegionTree(regionCode: string): PsgcProvince[] | null {
  if (!regionsByCode.has(regionCode)) return null;
  return psgc.provinces
    .filter((p) => p.regionCode === regionCode)
    .map((p) => ({
      code: p.code,
      name: p.name,
      cities: psgc.cities.filter((c) => c.provinceCode === p.code).map((c) => ({ code: c.code, name: c.name })),
    }));
}

/** Resolves a city/municipality code to its full, canonical place names. */
export function resolveCity(cityCode: unknown): ResolvedPlace | null {
  if (typeof cityCode !== "string") return null;
  const city = citiesByCode.get(cityCode);
  if (!city) return null;
  const province = provincesByCode.get(city.provinceCode)!;
  const region = regionsByCode.get(city.regionCode)!;
  return {
    regionCode: region.code,
    provinceCode: province.code,
    cityCode: city.code,
    region: region.name,
    province: province.name,
    city: city.name,
  };
}

/** "City of Makati" → "makati city", "San José (Pob.)" → "san jose". */
function fullKey(name: string) {
  return name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/\s*\(.*\)$/, "")
    .replace(/^city of (.+)$/, "$1 city")
    .trim();
}

/** Drops the "city" suffix: "makati city" → "makati". */
function baseKey(name: string) {
  return fullKey(name).replace(/ city$/, "");
}

/**
 * Best-effort match of free-text names (e.g. from OpenStreetMap reverse geocoding)
 * to a PSGC city code. Tries the full name first ("Quezon City" ≠ the towns named
 * "Quezon"), then without the "City" suffix. Returns null if unknown or ambiguous.
 */
export function matchCity(names: { city: string; province?: string }): string | null {
  const provinceKey = baseKey(names.province ?? "");

  for (const key of [fullKey, baseKey]) {
    const target = key(names.city);
    if (!target) return null;
    const candidates = psgc.cities.filter((c) => key(c.name) === target);
    if (candidates.length === 1) return candidates[0].code;
    if (candidates.length > 1) {
      const inProvince = candidates.filter(
        (c) => baseKey(provincesByCode.get(c.provinceCode)!.name) === provinceKey,
      );
      return inProvince.length === 1 ? inProvince[0].code : null;
    }
  }
  return null;
}

/** Name to send to geocoders: "City of Makati" → "Makati City". */
export function geocoderCityName(name: string) {
  return name.startsWith("City of ") ? `${name.slice(8)} City` : name;
}
